import LegalLayout from '../components/LegalLayout'

const SECCIONES = [
  { titulo: 'Naturaleza del Servicio, Alcance y Aceptación de Términos', arts: [
    'Artículo 1: Objeto y Definición de la Plataforma. La presente plataforma digital funciona exclusivamente como un directorio comercial y vidriera virtual geolocalizada destinada a vincular de manera directa a los consumidores con los comercios adheridos. La plataforma actúa como un canalizador de tráfico y un escaparate digital, no constituyendo una tienda online centralizada ni un marketplace de gestión directa por parte de los administradores del software.',
    'Artículo 2: Naturaleza del Proveedor Tecnológico (Rol B2B). El desarrollador y proveedor del software opera bajo un modelo estrictamente Business-to-Business (B2B) como prestador de servicios de infraestructura tecnológica y mantenimiento de sistemas. El proveedor no participa, intermedia, administra ni forma parte de las transacciones comerciales, contratos de compraventa, logística de envío, ni acuerdos particulares que se originen entre los comercios inscriptos y los compradores finales.',
    'Artículo 3: Aceptación Ineludible de los Términos. El acceso, registro o utilización de cualquier funcionalidad de la plataforma por parte de cualquier usuario (sea visitante, consumidor o comerciante titular de un local) implica la lectura y aceptación total, expresa e incondicional de los presentes Términos y Condiciones, así como de las Políticas de Privacidad vigentes. Si el usuario no estuviere de acuerdo con alguna de las cláusulas, deberá abstenerse de utilizar el servicio de forma inmediata.',
    'Artículo 4: Capacidad Legal y Autorización Comercial. Para registrar un comercio o utilizar las funciones de publicación dentro de la plataforma, el usuario declara bajo juramento ser mayor de edad, poseer plena capacidad legal para contratar y, en el caso de los comerciantes, contar con las habilitaciones comerciales y fiscales correspondientes exigidas por la legislación vigente de la jurisdicción donde opera su local físico.',
    'Artículo 5: Modificaciones y Actualizaciones del Servicio. Los administradores del sistema y el proveedor tecnológico se reservan el derecho absoluto de modificar, actualizar, suspender o discontinuar —total o parcialmente— las funcionalidades, la interfaz, los módulos o el acceso a la plataforma en cualquier momento, notificando a los usuarios mediante avisos internos o generales dentro de la propia aplicación, sin que ello genere derecho a reclamos, indemnizaciones o compensaciones de ninguna índole.',
    'Artículo 6: Disponibilidad del Servicio y Exclusión de Garantías (Uptime). La plataforma se provee "tal como está" y "según disponibilidad". El proveedor tecnológico y los administradores no garantizan que el servicio funcione de manera ininterrumpida, libre de errores, virus o fallas técnicas temporales derivadas de tareas de mantenimiento, actualizaciones de software, problemas de conectividad o cortes en los proveedores de infraestructura en la nube. Queda expresamente excluida cualquier indemnización por lucro cesante o daños derivados de interrupciones temporales del servicio.',
    'Artículo 7: Limitación Geográfica y Ámbito de Aplicación. El alcance operativo y la visibilidad de los comercios dentro del directorio están estrictamente limitados al territorio Argentino. La plataforma no asume compromiso ni obligación de expandir el servicio a otras regiones geográficas, quedando a criterio exclusivo de la administración la incorporación de nuevos sectores o zonas comerciales.',
    'Artículo 8: Propiedad Intelectual del Software y la Interfaz. Todo el código fuente, la arquitectura de base de datos, el diseño de la interfaz de usuario, los logotipos, la estructura lógica de navegación y los componentes visuales de la plataforma son propiedad exclusiva del desarrollador y proveedor tecnológico. Queda terminantemente prohibida la reproducción total o parcial, ingeniería inversa, copia no autorizada, extracción masiva de datos (web scraping) o comercialización de la tecnología subyacente sin la autorización previa y por escrito.'
  ]},
  { titulo: 'Registro de Usuarios, Autenticación y Seguridad de Cuentas', arts: [
    'Artículo 9: Registro y Creación de Cuenta. Para utilizar las funcionalidades de gestión de inventario, control de stock y administración de tiendas en StockShop, el usuario deberá registrarse obligatoriamente mediante una cuenta de correo electrónico válida y activa, autenticada con contraseña propia o a través de proveedores externos confiables como Google/Gmail. El usuario se compromete a proporcionar información veraz, exacta y actualizada durante el proceso de registro.',
    'Artículo 10: Responsabilidad y Confidencialidad de las Credenciales. El usuario es el único y exclusivo responsable de mantener la confidencialidad de sus credenciales de acceso, contraseña y métodos de autenticación vinculados a su cuenta. Cualquier actividad, movimiento de stock, modificación de precios o transacción realizada bajo las credenciales del usuario se considerará efectuada por este último, eximiendo a los desarrolladores de cualquier responsabilidad por accesos no autorizados derivados de negligencia del usuario.',
    'Artículo 11: Obligación de Notificación por Uso No Autorizado. El usuario se obliga a notificar de forma inmediata a los administradores y soporte técnico de StockShop ante cualquier uso no autorizado de su cuenta, brecha de seguridad detectada o sospecha de vulneración en sus credenciales de acceso. La falta de notificación oportuna deslinda a los desarrolladores de responsabilidades por la pérdida de datos o alteraciones en los inventarios.',
    'Artículo 12: Cuentas Múltiples y Roles de Usuario dentro del Negocio. En caso de que el software permita la creación de subcuentas, asignación de roles o accesos para empleados y colaboradores dentro de un mismo comercio, el titular principal de la cuenta registrada será civil y administrativamente responsable de todas las acciones ejecutadas por los usuarios que haya autorizado bajo su estructura comercial.',
    'Artículo 13: Derecho de Suspensión y Baja de Cuentas por los Administradores. Los desarrolladores de StockShop se reservan el derecho absoluto de suspender, bloquear temporalmente o dar de baja definitiva cualquier cuenta de usuario que infrinja las presentes normas de seguridad, que muestre comportamientos anómalos que pongan en riesgo la integridad de la base de datos, o que utilice la plataforma para fines ilícitos, sin previo aviso y sin que ello genere derecho a indemnización alguna.',
    'Artículo 14: Propiedad de los Datos Comerciales y del Inventario. Los datos de stock, catálogos, precios, registros de ventas e información de tiendas cargados por el usuario pertenecen a su respectivo comercio. Sin embargo, el usuario otorga a StockShop una licencia mundial, no exclusiva y limitada para procesar, almacenar, respaldar y visualizar dichos datos estrictamente con el fin de proveer y mejorar el funcionamiento operativo del software.',
    'Artículo 15: Inactividad Prolongada y Depuración de Cuentas. StockShop se reserva el derecho de archivar, suspender o eliminar cuentas de usuario, junto con sus registros asociados e inventarios, que permanezcan en estado de inactividad total por un período consecutivo superior a los 180 (ciento ochenta) días, previa notificación al correo electrónico registrado, con el fin de optimizar los recursos y la seguridad de la base de datos.',
    'Artículo 16: Exención de Responsabilidad por Exactitud de Datos e Inventarios. StockShop es una herramienta de asistencia tecnológica para el control de stock, pero la carga, veracidad, actualización y control físico del inventario recaen absoluta y exclusivamente sobre el usuario. Los desarrolladores no asumen ninguna responsabilidad por diferencias de inventario, pérdidas económicas, quiebres de stock o errores derivados de una mala carga de datos, fallas en la conectividad del usuario al momento de sincronizar, o un uso indebido de los módulos. El usuario es el único responsable de realizar respaldos externos de su información crítica si así lo considerase necesario.'
  ]},
  { titulo: 'Contenidos del Usuario, Moderación de Archivos y Propiedad Intelectual', arts: [
    'Artículo 17: Titularidad y Responsabilidad del Contenido Subido. Todo texto, imagen, fotografía, catálogo, descripción o archivo digital (en formatos permitidos tales como JPG, PNG, JFIF y WebP) subido, publicado o almacenado por el usuario en StockShop es de su absoluta y exclusiva autoría y responsabilidad. Los desarrolladores no moderan activamente ni validan de forma previa la legalidad, veracidad o procedencia de cada archivo cargado, recayendo toda consecuencia legal sobre el comerciante emisor.',
    'Artículo 18: Formatos Permitidos y Prohibición de Archivos Maliciosos. El sistema acepta estrictamente archivos de imagen bajo formatos estándar autorizados (JPG, PNG, JFIF y WebP). Queda terminantemente prohibido intentar subir archivos ejecutables, scripts ocultos, documentos comprimidos o cualquier formato no autorizado que pueda comprometer la seguridad de los servidores o la integridad de la base de datos. Cualquier intento de vulneración será bloqueado automáticamente y derivará en la baja inmediata de la cuenta.',
    'Artículo 19: Prohibición Absoluta de Contenido Ilegal o Sensible (Tolerancia Cero). Se prohíbe de manera absoluta la carga, difusión, almacenamiento o exposición en la plataforma de cualquier contenido que vulnere leyes vigentes, infrinja derechos de menores de edad, contenga material pornográfico, violento, extorsivo, fraudulento, o cualquier forma de contenido inapropiado o ilícito. Ante la detección o reporte de este tipo de material, el sistema procederá a su eliminación automática y al bloqueo permanente del infractor, reservándose el derecho de poner los antecedentes a disposición de las autoridades competentes.',
    'Artículo 20: Propiedad Intelectual, Marcas Registradas y Copias (Réplicas). El usuario declara y garantiza que cuenta con los derechos necesarios, autorizaciones o licencias para comercializar y publicitar los productos exhibidos en su inventario. StockShop no avala, fomenta ni se hace responsable por la comercialización de productos apócrifos, falsificaciones o infracciones a marcas registradas. La responsabilidad civil, comercial y penal por el uso no autorizado de marcas comerciales recae de forma exclusiva sobre el comerciante que realiza la publicación.',
    'Artículo 21: Protocolo de Retiro por Infracción (Notice and Takedown). Ante cualquier notificación fehaciente de presunta infracción de derechos de propiedad intelectual, marcas registradas o contenidos indebidos por parte de un titular legítimo o autoridad competente, StockShop aplicará un protocolo de baja inmediata, procediendo a remover el contenido y/o suspender el comercio involucrado en un plazo no mayor a 24 horas hábiles, sin que ello genere derecho a reclamo o indemnización para el usuario afectado.',
    'Artículo 22: Facultad de Moderación Automatizada y Auditoría. StockShop se reserva el derecho —mas no la obligación— de implementar herramientas automáticas de escaneo, algoritmos de detección de contenido, filtros de archivos o revisiones aleatorias sobre la información y los archivos multimedia cargados por los usuarios. La aplicación de estos mecanismos de control no transfiere la responsabilidad del contenido al proveedor tecnológico, subsistiendo la obligación y culpa exclusiva del comerciante por el material publicado en su espacio de inventario.'
  ]},
  { titulo: 'Transacciones, Pasarelas de Pago, Eximición Fiscal y Jurisdicción', arts: [
    'Artículo 23: Naturaleza Descentralizada de los Pagos y Transacciones. StockShop no procesa, intermedia, retiene ni custodia fondos derivados de las operaciones comerciales entre los comerciantes y sus clientes. Las pasarelas de pago (tales como Mercado Pago u otras similares) son configuradas, operadas y vinculadas de manera directa y exclusiva por cada comercio bajo su propia responsabilidad. StockShop no es entidad financiera ni proveedor de servicios de pago (PSP), deslindando al software de cualquier reclamo por cobros fallidos, contracargos (chargebacks), disputas o retenciones de dinero.',
    'Artículo 24: Responsabilidad Fiscal, Tributaria y Facturación. El cumplimiento de las obligaciones fiscales, impositivas, previsionales y de facturación legal (emisión de tickets, facturas electrónicas, pago de tributos nacionales, provinciales o municipales como AFIP/ARBA, etc.) corresponde única y exclusivamente al comercio inscripto. StockShop no emite facturación en nombre de los locales ni asume responsabilidad alguna por la evasión, omisión o mala liquidación de impuestos por parte de los usuarios de la plataforma.',
    'Artículo 25: Limitación Máxima de Responsabilidad Económica. En el supuesto caso de que un juez o autoridad competente determinara judicialmente alguna responsabilidad civil o económica por parte de los desarrolladores de StockShop, la indemnización total máxima a pagar por cualquier concepto no superará bajo ninguna circunstancia el monto equivalente al abono mensual efectivamente pagado por el usuario a la plataforma en los últimos tres (3) meses previos al reclamo.',
    'Artículo 26: Modificaciones de los Términos y Condiciones. Los desarrolladores podrán modificar los presentes Términos y Condiciones en cualquier momento, publicando las versiones actualizadas dentro de la plataforma. El uso continuado del software tras la publicación de los cambios implicará la aceptación tácita de las nuevas condiciones por parte del usuario.',
    'Artículo 27: Jurisdicción y Ley Aplicable. Para todos los efectos legales derivados de la interpretación, validez y cumplimiento de los presentes Términos y Condiciones, las partes se someten expresamente a la legislación vigente de la República Argentina y a la competencia de los Tribunales Ordinarios correspondientes al domicilio legal del desarrollador o proveedor principal de la tecnología, renunciando a cualquier otro fuero o jurisdicción que pudiera corresponderles.'
  ]},
  { titulo: 'Espacios Publicitarios y Alianzas Estratégicas', arts: [
    'StockShop se reserva el derecho de comercializar espacios publicitarios dentro de la plataforma y de ofrecer a los Usuarios recomendaciones o anuncios segmentados de proveedores de insumos, marcas aliadas y servicios complementarios. La segmentación de dicha publicidad podrá basarse en los patrones de consumo, rubro y rotación de stock declarados o inferidos en el uso de la aplicación, sin que esto implique una cesión o venta de los datos personales del Usuario a terceros. El Usuario acepta recibir dichas propuestas comerciales en el marco de la operatividad del ecosistema B2B.'
  ]}
]

export default function Terminos() {
  return <LegalLayout titulo="Términos y Condiciones" actualizado="Octubre 2026" secciones={SECCIONES} />
}